# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

[project]
name = "noaa-rfc"
version = "0.1.0"
description = "NOAA River Forecast Center Seasonal Forecasts"
readme = "README.md"
authors = [
    { name = "Colton Loftus", email = "70598503+C-Loftus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "src/noaa_rfc/noaa_rfc_stations_by_region.csv" = "src/noaa_rfc/noaa_rfc_stations_by_region.csv" }
