# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

[project]
name = "useace"
version = "0.1.0"
description = "EDR mappings for the API for the US army corps of engineers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = true

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["useace"]

[tool.hatch.metadata]
allow-direct-references = true
