# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

[project]
name = "rise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = true

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rise"]

force-include = { "rise/generated/Reservoirs_and_Capacity_Data.json" = "rise/generated/Reservoirs_and_Capacity_Data.json" }

artifacts = [
    "*.json"
]

[tool.hatch.metadata]
allow-direct-references = true
